apiVersion: v1
kind: ServiceAccount
metadata:
  name: stripefs-csi-driver
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stripefs-csi-driver
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stripefs-csi-driver
subjects:
  - kind: ServiceAccount
    name: stripefs-csi-driver
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: stripefs-csi-driver
  apiGroup: rbac.authorization.k8s.io
